# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'front' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Stub for removed hermes V1 inspector API (hermes/inspector/RuntimeAdapter.h)
    # Required by react-native-reanimated 3.x with newer hermes-engine
    stub_dir = "#{installer.sandbox.root}/Headers/Public/hermes-engine/hermes/inspector"
    FileUtils.mkdir_p(stub_dir)
    stub_path = "#{stub_dir}/RuntimeAdapter.h"
    unless File.exist?(stub_path)
      File.write(stub_path, <<~STUB)
        // Stub for removed hermes V1 inspector API
        #pragma once
        #include <hermes/hermes.h>
        namespace facebook::hermes::inspector_modern {
        class RuntimeAdapter {
         public:
          virtual ~RuntimeAdapter() = default;
          virtual facebook::hermes::HermesRuntime& getRuntime() = 0;
          virtual void tickleJs() = 0;
        };
        } // namespace facebook::hermes::inspector_modern
      STUB
    end
  end
end
